# Generated by Django 4.2.5 on 2023-09-29 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_remove_story_content_story_audio_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('difficulty_rating', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='stories.module'),
        ),
    ]
