import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AppBar from "@mui/material/AppBar";
import Typography from "@mui/material/Typography";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppBar position="static">
          <div className="h-[66px] px-4 py-2 flex items-center">
            <Typography variant="h6">
              <span className="italic">Warrior English</span>
            </Typography>
          </div>
        </AppBar>
        <div className="h-[calc(100vh-66px)]">{children}</div>
      </body>
    </html>
  );
}
